"""Alert data models for the Alert Generator Agent.

This module defines the data structures for fraud alerts, provenance tracking,
and detection rules produced by the Alert Generator agent:
- FraudAlert: the primary alert structure with TTP details and severity
- AlertProvenance: traceability from alert back to original dark web source
- DetectionRule: recommended detection rules (YARA, Sigma, custom)
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional


# Valid alert types for FraudAlert
ALERT_TYPES = ("ttp_alert", "campaign_alert", "summary_digest")

# Valid severity levels for FraudAlert
SEVERITY_LEVELS = ("low", "medium", "high", "critical")

# Valid rule types for DetectionRule
RULE_TYPES = ("yara", "sigma", "custom")


@dataclass
class AlertProvenance:
    """Traceability information linking an alert to its original source.

    Provides a full chain of custody from the raw dark web content
    through the processing pipeline to the generated alert.
    """

    original_source_url: str
    crawl_timestamp: datetime
    s3_artifact_key: str  # Reference to raw artifact in S3
    processing_chain: list[str] = field(default_factory=list)  # Agent IDs in processing order


@dataclass
class DetectionRule:
    """A recommended detection rule generated by the Alert Generator.

    Can be a YARA rule (file/memory scanning), Sigma rule (log detection),
    or a custom rule format for institution-specific detection systems.
    """

    rule_type: str  # "yara" | "sigma" | "custom"
    rule_content: str
    confidence: float  # 0.0 to 1.0

    def __post_init__(self) -> None:
        if self.rule_type not in RULE_TYPES:
            raise ValueError(
                f"Invalid rule_type '{self.rule_type}'. Must be one of: {RULE_TYPES}"
            )
        if not (0.0 <= self.confidence <= 1.0):
            raise ValueError(
                f"confidence must be between 0.0 and 1.0, got {self.confidence}"
            )


@dataclass
class FraudAlert:
    """A structured fraud intelligence alert produced by the Alert Generator.

    Contains the TTP description, affected institutions, severity assessment,
    recommended detection rules, and provenance tracing back to the original source.
    """

    alert_id: str
    alert_type: str  # "ttp_alert" | "campaign_alert" | "summary_digest"
    severity: str  # "low" | "medium" | "high" | "critical"
    ttp_description: str
    affected_institutions: list[str]
    recommended_detection_rules: list[DetectionRule]
    related_intelligence: list[str]  # STIX object IDs
    provenance: AlertProvenance
    created_at: datetime
    sns_message_id: Optional[str] = None  # SNS publish confirmation

    def __post_init__(self) -> None:
        if self.alert_type not in ALERT_TYPES:
            raise ValueError(
                f"Invalid alert_type '{self.alert_type}'. Must be one of: {ALERT_TYPES}"
            )
        if self.severity not in SEVERITY_LEVELS:
            raise ValueError(
                f"Invalid severity '{self.severity}'. Must be one of: {SEVERITY_LEVELS}"
            )
